# Generated by Django 5.1.2 on 2024-10-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_inbox_options_user_biography"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="biography",
            field=models.CharField(
                default="This user has thus far opted to maintain an air of mystery.",
                max_length=1000,
            ),
        ),
    ]
