# Generated by Django 5.1.2 on 2024-11-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_user_biography"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="First name", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="Last name", max_length=50),
        ),
    ]
