# Generated by Django 5.1.2 on 2024-11-11 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0006_tag_conversation_message_userpost_posttagmapping_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={},
        ),
    ]
