# Generated by Django 5.1.2 on 2024-11-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0007_alter_conversation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tags",
            field=models.ManyToManyField(max_length=6, to="database.tag"),
        ),
        migrations.AddField(
            model_name="userpost",
            name="length",
            field=models.IntegerField(default=6),
        ),
    ]
