# Generated by Django 5.1.2 on 2024-11-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_user_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tags',
        ),
    ]
